const config = {
  SUPPRESS_BACKEND_ERRORS: false,
  SERVER_URL: "SERVER_URL",
  NODE_SERVER_URL: "NODE_SERVER_URL",
  DICTATION_BE_URL: "DICTATION_BE_URL",
  X_API_KEY: "X_API_KEY",
  PUBLIC_USER_ID: "PUBLIC_USER_ID",
  AG_GRID_LICENSE_KEY: "AG_GRID_LICENSE_KEY",
};

export const SUPPRESS_BACKEND_ERRORS = config.SUPPRESS_BACKEND_ERRORS;
export const SERVER_URL = config.SERVER_URL;
export const NODE_SERVER_URL = config.NODE_SERVER_URL;
export const DICTATION_BE_URL = config.DICTATION_BE_URL;
export const X_API_KEY = config.X_API_KEY;
export const PUBLIC_USER_ID = config.PUBLIC_USER_ID;
export const AG_GRID_LICENSE_KEY = config.AG_GRID_LICENSE_KEY;
